const VILLAGES = [
  "Bandafassi Peulh",
  "Silling",
  "Bandafassi Tanda",
  "Meressi",
  "Baytilaye",
  "Boundoucondi",
  "Nathia",
  "Djindji Bassari",
  "Djindji",
  "Wakiralé",
  "Habibou",
  "Dar Salam",
  "Ibel",
  "Damboucoye",
  "Itato",
  "Newdouyel",
  "Tepéré Diantoun",
  "Thiancoun Malal",
  "Iwol",
  "Laminia",
  "Landé Baïtyle",
  "Hamady Herry",
  "Landiéni Peulh",
  "Landiéni Tanda",
  "Nianghé",
  "Santanco",
  "Tacourou",
  "Patassy",
  "Samécouta",
  "Kénioto Diakha",
  "Kénioto Peul",
  "Syllacounda Diakha",
  "Taïfa",
  "Syllacounda Peulh",
  "Sinthiouroudji",
  "Thiabédji",
  "Ndandaye",
  "Samal",
  "Thiokéthian",
  "Guingara",
  "BALA",
  "DAROU NDIOUFENE",
  "DIABY",
  "DIDE",
  "DIOULANGUEL",
  "FASS KOUTHIA (FASS GOUNASS)",
  "GAYE PARADJI",
  "GOUREL BARTHIAM (NDIOUM DIAWARA)",
  "GOUREL KONTE (GOUREL ADAMA)",
  "H1 NDIOUM DAOUDA",
  "H1 NEMA",
  "H1 PROJET NGUIDIVOL",
  "H1 SINTHIOU BATHILY",
  "H1 SINTHIOU SALIF THIAM",
  "H5 HOFERA (GOUREL YORO)",
  "KAHEL (DIYALA II)",
  "KOUTHIAKHASSE (KOUTIA)",
  "LOUNTCHI",
  "MADINA TOBENE (NDONGO TOP)",
  "MBANGOL",
  "NDIAM SIBY",
  "NDIOUM SAMBA CAMARA",
  "NDIOUM SAMBA GUILLE (NDIOUM DEMBA GUILLE)",
  "NDOMBOTO (SINTHIOU DIAGUILI)",
  "NGUIDIVOL",
  "PASS KOUTIA",
  "SABOUCIRE",
  "SINTHIOU BACAR KOBOR II (DIAGUILI)",
  "SINTHIOU BAMBA",
  "SINTHIOU DIOKHE (FRETHIE)",
  "SINTHIOU MAKA",
  "THIARA",
  "TIVAOUANE",
  "WIGUE I",
  "WIGUE II (GOUREL YOUNOUSSA)",
  "Bembou",
  "Dioulafoundou",
  "Massa Massa",
  "Badioula",
  "Madina Dantila",
  "Pondala",
  "Diakhaba",
  "Boussankhoba",
  "Koumboutourou",
  "Somaya",
  "Diakha Madina",
  "Faraba",
  "Baitilaye",
  "Balori",
  "Fodebinea",
  "Samekhoto",
  "Sanela",
  "Nafadji",
  "Boboti",
  "Garebourea",
  "Satadougou",
  "Moussala",
  "Bambadji",
  "Kharakhena",
  "Kolia",
  "Lingueya",
  "Sansamba",
  "Sansela",
  "Kondokhou",
  "Barabiri",
  "Dioby",
  "Dalafing",
  "BADON",
  "BAFOUNDOU",
  "BAGNOMBA",
  "BANTAKOCOUTA",
  "BANTATA MANDINGUE",
  "BANTATA TANDA",
  "BANCAKOKHOCO",
  "BATRANKÉ",
  "BRANDOUFARY",
  "DAR SALAM DALABA",
  "H1 BANTAKOKHOTO",
  "H1 DALAKOYE",
  "H1 FANKOLY",
  "H1 FOLONKOTO",
  "H1 FOUKHOTO (BADIAN II)",
  "H1 KENIEKENIE",
  "H1 KOLON",
  "H1 KOULOUNTOU",
  "H1 KOUMOUSSABOTO",
  "H1 LAME",
  "H1 LINGUEKOTO",
  "H1 PROJET PONON",
  "H1 SINDAKHA",
  "H1 SINTHIOU ROUDJI",
  "H1 THIOBO",
  "H2 BAMBOYA",
  "H2 BARAFOUTE",
  "H2 DIENDJI BASSARI (OUBADJI)",
  "H2 KOUNDANG",
  "H2 KOUTOUFINKOTO",
  "H2 NIARICONDON",
  "H2 SEKHOTO",
  "H2 WASSADOU",
  "H3 SAINT ETIENNE",
  "H4 SENOTHIE",
  "KABATE GUINDA",
  "KANOUMERING",
  "MAKO",
  "MANIANKANTY (KEREKONKO)",
  "MAROUGOUDING",
  "MAROUGOUKOTO (BADIAN I)",
  "NEGUEBAKHO MIRABOUGOU",
  "NGARY (ONGAR)",
  "NIEMENIKE",
  "SEGUEKO BASSARI",
  "SEGUEKO PEULH",
  "SIBIKILING",
  "TAMBANOUMOUYA",
  "TEMASSOU",
  "TENKOTO TANDA ET MANDINGUE",
  "TIKANKALY",
  "TOMBORONKOTO",
  "TOUBA DIAKHA",
  "AFIA DANDEMAY",
  "BAMBAYA",
  "BAMBOYA",
  "BARA (ROUNDE BARA)",
  "BOWAL",
  "DIALAYA",
  "DIANHERY (YOROYA)",
  "DIMBOLI",
  "FODECOUNDA",
  "H1 AFIA II",
  "H1 BAMBAYA LABOUR",
  "H1 BARA",
  "H1 BASSAKHO",
  "H1 DAROU SALAM",
  "H1 DIALAYA II",
  "H1 FOUYA",
  "H1 GOUNDIOUROU",
  "H1 LEFALODJI",
  "H2 BAKHO",
  "H2 DIAGUIRI PONT",
  "H2 NIAMANA",
  "H2 SAIKOU (DARA EL HADJI MALICK SY)",
  "H2 THIANGOL YAYA",
  "H3 KAFORY DIALONKE",
  "H3 SAMBA NDIAYE",
  "H6 SINTHIOU MALEM",
  "KAFORY",
  "LINDIANE",
  "MALEME",
  "MALINDA",
  "MANIAFE",
  "MEDINATOU",
  "TOGUE",
  "VELINGARA",
  "WOULABA",
  "H1 BOUSSOURA",
  "LEYEMAYO",
  "H5 SINTHIOU SEYDOU",
  "H6 DIALLA BATAMA",
  "H4 DIAGUIRI BASSARI",
  "TAMBACOUMALA",
  "LINGUEKHOTO",
  "H3 SINTHIOU MAMOUDOU",
  "AFIA I (THIABE CARE)",
  "AFIA II",
  "BOUSSOURA (MAMADOU BOUNDOU)",
  "DANDE",
  "DINDEFELO",
  "DIOGOMA NANDOUMARI",
  "H1 BOUNDOU DOUDOUKE",
  "H1 MBOULAYE",
  "H1 YAMOUSSA DIAKHA",
  "H2 BADALLAH",
  "H2 TEPERE DIANTOUNG",
  "H3 NEWDOU (BOUCHRA)",
  "PELEL KENDESSA",
  "SAGARIDJI BADIARI",
  "THIANGUE",
  "YAMOUSSA SEGOU",
  "BOULAKO",
  "SEGOU",
  "Banfara Mossi",
  "Dialoube",
  "Diarra",
  "Diarra (Sinthiou.Ngourou)",
  "Diyabougou Sakho",
  "Gambi",
  "Godioyel",
  "Hamdalaye Diouhe",
  "Innalah",
  "Koar",
  "Medina Moussa",
  "Medina Ouolof",
  "Naoude",
  "Ngarivol",
  "Noumouyel",
  "Saboussire",
  "Sare Niana",
  "Sare Niana 2",
  "Sinthiou Guidivol",
  "Sinthiou Sada Ly",
  "Sinthiou.Bocar Sada",
  "Sira Corobougou",
  "Tambanding",
  "ALAHINA BAMBARA",
  "ALAHINA MAURE",
  "ALAHINA PEULH",
  "ALALEVI",
  "BEMA",
  "BORDE DIAWARA",
  "BORDE FOULBE",
  "DIABAL",
  "FALOBOULA",
  "GABOU",
  "GOUNIANG",
  "GOUREL DIALOUBE",
  "GOUREL MANDIOU",
  "GUETHIE",
  "H1 BILE FOULBE",
  "H1 MAYEL NDAMARDY",
  "H2 BILE BOBORE",
  "HAMEAU GOUREL OUROULBE",
  "KADIEL SAMBOUBOU",
  "KADIEL SEOUDOU",
  "KAHE",
  "KANDA BORSA",
  "LOMBOL GANDJI",
  "LOMBOL TOBITO",
  "MARSA",
  "MAYEL AMATH",
  "MAYEL FILY",
  "MEDINA ABDOUL",
  "MEDINA CARREFOUR",
  "MISSIRAH SAMBA YIDE",
  "MORIBOUGOU",
  "OLOLDOU BOUNDOU",
  "OLOLDOU ESCALE",
  "SAMBA GOURO",
  "SAMBA KONTAYE",
  "SAMBA NIAME (SAMBA DIAME)",
  "SARE FADOUBE",
  "SENO SIMBING",
  "SINTHIOU MADINA",
  "SINTHIOU SEYDOU DORO",
  "SINTHIOU THINGOLEL",
  "SIRA BAIDY (GOUREL BAIDY)",
  "SIRA DOUNDOU",
  "SIRA KALIDOU (SIRA DEMBOYE)",
  "SIRA MAMADOU BOCAR",
  "SIRA NGADA",
  "SIRA SIMBING",
  "SIRA SISSIBE",
  "ALLABOUGOU",
  "ARDOULAYE WASSIHATOU",
  "BAGADADJI (BOUNKILING)",
  "BAMBADINKA",
  "BIRA (BIRA TABA)",
  "BOULACOUNDA BOLOL (BOULACOUNDA PEULH)",
  "DAROU SALAM (BOUBOU BA)",
  "DIAWOCOUNDA (LAREDJI PEULH)",
  "DIYABOUGOU II",
  "GADAPARA",
  "GADAPARA ( SINTHIOUROU BOYE )",
  "GOULOUMBOU",
  "GUINGUINEO (MEDINA BAMBARA)",
  "HAMDALAYE SEYNI (SARE SEYNI)",
  "HAMDALLAYE (NDIAPALDE)",
  "HAMDALLAYE PONT (MONTOUGOU)",
  "HAMDALLAYE SALOUM SEYDI",
  "HAMDALLAYE TESSANG",
  "KELECOUNDA",
  "KENIEKENIEBA",
  "KOAR ALADJI",
  "KOAR I (KOAR MBAYLARY)",
  "KOAR II (SINTHIOU SAMBA KOUROU)",
  "KOAR III(KOAR PROJET)",
  "KOAR YERO DIALLO",
  "KODIAM",
  "KOLONDIARA (GOUREL BOCAR)",
  "LAREDJI MANDINGUE",
  "LOUGUE NIALBY",
  "MADIALY",
  "MADINA BOULACOUNDA (GOUREL YOBA)",
  "MADINA YERO (SITAOULE YERO DIATTA)",
  "MAHINA COURA",
  "MEDINA ALY (SARE ALY)",
  "MEDINA DIAKHA",
  "MEDINA DIAN",
  "MEDINA MAMOUDOU (BARKAYEL)",
  "MISSIRAH",
  "MISSIRAH TABADIAN (B. SOUCOUTO) (B. TABADIANG)",
  "MISSIRAH TONGOUDE (SINTHIAN TONGOUDE)",
  "MOUKOUTY",
  "MOUNTOBOU (MOUNTOB)",
  "NEMA HAMADY (SARE HAMADY)",
  "NEMA I (NEMA SAMBOU)",
  "NGUENE I (NGUENE SERERE)",
  "NGUENE PEUL",
  "NIAOULE MBAYGOU",
  "NIAOULE TANOU",
  "OUNDOUNDOU AMEROU",
  "PAKALY",
  "PATHIOU",
  "RAMATOULAYE (SARE BOUNE)",
  "SAAL",
  "SABY MOULESSY",
  "SAFALOU I",
  "SAFALOU II",
  "SANKAGNE I",
  "SANKAGNE II",
  "SARE ILO DEME",
  "SARE OUMAR LY (GOUMALOU)",
  "SARE PATHE",
  "SARE PATHE FOUGOULOU",
  "SARE THIDY (MAKABE SIDY)",
  "SAROUDIA",
  "SINTHIOU BARA",
  "SINTHIOU KOLONDING",
  "SINTHIOU THIERNO",
  "SITAOULE ISSAC",
  "SOCOUNDA ADIAAF",
  "TABADIAN DIALIKO",
  "TALIBOULOU FINANKE",
  "TAYE DIABY",
  "TEMENTO MALEDE",
  "TIMBAFOULOU",
  "TOUBA",
  "VELINGARA BIDIANKOTO",
  "VELINGARA LEGUEL (SARE BOUBOU)",
  "VELINGARA OUMAR",
  "VELINGARA PONT",
  "VELINGARA YAYA (SITAOULE)",
  "H1 BAGADADJI",
  "H1 BARADJICOUNDA",
  "H1 DIMANDING",
  "H1 DJIDA (CR BALA)",
  "H1 FASS",
  "H1 GABON",
  "H1 GALLE TOUNKO SOW",
  "H1 GOUREL SEKOUDIA",
  "H1 PATHIOU TOUMBOU",
  "H1 PROJET ELEVAGE SOPELA",
  "H1 SARE NIANA",
  "H1 SINTHIOU NDIAPALDE",
  "H2 HAFIA",
  "H2 MADINA NIAGOU",
  "H2 MAMPATODI ",
  "H2 SIKASSO",
  "H2 SINTHIOU KABADA",
  "H2 SINTHIOU NDIOBO",
  "H2 SINTHIOU SAMBA",
  "H3 SARE NDOUGUE",
  "H3 SINTHIOU SAMBA TALL",
  "H4 KANTHIALA",
  "BONDJI FOULABE",
  "BONDJI MEDOUWORY",
  "BONDJI SINTHIANE",
  "CARREFOUR SARE HAMADI",
  "DIAMWELY",
  "DIAMWELY GARAGE",
  "DIEKOULANE",
  "GALLADE",
  "GANDE",
  "H1 BELI",
  "H1 DIEYBABA",
  "H1 MBOMOYABE",
  "H1 SABOU SIRE SONINKE",
  "H1 SALAMATOU",
  "H2 GOUREL DAO",
  "H2 GOUREL SAMBA SOW",
  "H2 LOUBOUGAL",
  "H3 BANDIAGARA",
  "MANAEL",
  "MANTHIABOU",
  "MOUDERY",
  "NAMANDY",
  "OUNDOUM BABA",
  "SABOUCIRE FOULBE",
  "TOURIME",
  "TUABOU",
  "YELINGARA",
  "Botou",
  "Boucaricounda Diallo",
  "Boucaricounda Manding",
  "Boudou Boundou",
  "Damba Missirah",
  "Dialacoro",
  "Diam Diam Ndawene",
  "Diombodina Manding",
  "Guirigara",
  "Idakoto",
  "Idakoto Pont (Pondalla)",
  "Kerewane Tamba Sangar",
  "Koromadji",
  "Kouthia Kouroumba",
  "Licounda Mandingue",
  "Licounda Peulh",
  "Maribougou",
  "Mayel Diby",
  "Medina Diakha",
  "Medina Diam Diam",
  "Medina Maboube",
  "Medina Mamoudou",
  "Medina Moussa",
  "Medina Niana I",
  "Medina Sarakhole",
  "Missirah",
  "Nema I",
  "Nema Ii",
  "Padah Peulh",
  "Sadioboulou Peulh",
  "Sadioboulou Thiombel",
  "Sambadian Counda",
  "Samecouta Mandingue",
  "Samecouta Peulh",
  "Sare Dounguel",
  "Sare Faring",
  "Sare Ngaye Ba",
  "Sare Sabake Thiewal",
  "Sinthiou Balla",
  "Sinthiou Damba",
  "Sinthiou Diadie",
  "Sinthiou Dialigue",
  "Sinthiou Diaouli",
  "Sinthiou Faring",
  "Sinthiou Gayo",
  "Sinthiou Inadina",
  "Sinthiou Kouna",
  "Sinthiou Maleme",
  "Sinthiou Mayel",
  "Sinthiou Noppi",
  "Sinthiou Ousmane Diallo",
  "Sinthiou Souna",
  "Sinthiou Diame Sow",
  "Sinthiou Yoro Deme (Bogal)",
  "Sirimandiala Boye",
  "Sirimandiala Fode",
  "Sitadian",
  "Thiaor",
  "Thioro Gallo",
  "Thiorobougou Bambara",
  "Thiorobougou Peulh",
  "Touba Fall",
  "Velingara Sabacke",
  "Velingara Samba",
  "Velingara Samba Ndawene",
  "Maleme Koto",
  "Touba Ndawene",
  "Botou",
  "boucaricounda",
  "boucaricounda demba",
  "boudouboudou",
  "bousra",
  "damba missira",
  "dialacoro 2",
  "dialaly",
  "diombodina",
  "gallobougou",
  "gorgui beye",
  "hamdalaye diadie",
  "hamdalaye faring",
  "idacoto pont",
  "idacoto village",
  "inadina",
  "karamatou",
  "kouthia kroumba",
  "lambabougou2",
  "lycounda",
  "lycounda manding",
  "madina diakha",
  "madina niama",
  "madina niana",
  "madina sarakole",
  "madyna sylla",
  "marikababougou",
  "pada",
  "padayel",
  "sambadiancounda",
  "samecouta manding",
  "sare dialigue",
  "sare diawly",
  "sare gayo",
  "sare maka",
  "sare moussa",
  "sare niana",
  "sare nopi",
  "sare ousmane",
  "sinthiou adama",
  "sinthiou bala",
  "sinthiou boubou",
  "sinthiou boubou dem",
  "sinthiou demba",
  "sinthiou diadia",
  "sinthiou foula",
  "sinthiou harigale",
  "sinthiou ousmane",
  "sinthiou tidiane",
  "sirmandiala boy",
  "st abdourahmane",
  "st samba ba",
  "taw fekh",
  "thioro galo sabake",
  "thioro peulh",
  "thiorobougou",
  "velingara sabake",
  "BOUROUKOU",
  "BOUSTANE MOURIDE",
  "DOUTOTO MANDING",
  "KANAPECOTO",
  "KEREWANY NGOYE",
  "MEDINA ABDOURAHMANE",
  "MINDE BOBA MANDING",
  "MINDE BOBA PEUL",
  "PENDA CARRE PEU",
  "SARE DEMERY",
  "SARE GUEDA",
  "SARE SIDY I",
  "SINTHIOU NDIOGA SANE",
  "SINTHIOU OURO SOCK",
  "SINTHIOU SOUKA I",
  "SINTHIOU SOUKA II",
  "SINTHIOUCOUNDA",
  "SOTOCOTO BOULOU",
  "VELINGARA DIATE DIALLO",
  "BAMBACO",
  "BANTANDIENKE",
  "COLINKAN",
  "COUCOUCONLONG MANDING",
  "COUCOUCONLONG PEUL",
  "DEMBACOUNDA",
  "DOUTA BASSY",
  "GOBOUCOUNDA",
  "KANDECOUNDA",
  "MANDIANCOUNDA",
  "MEDINA COLY",
  "SARE DIAMERY SANDING",
  "SARE SIDY II",
  "SARE SOUNA",
  "SEORO",
  "SINOU OULY",
  "SINTHIOU BOYE DIALLO",
  "SINTHIOU DIADIA BA",
  "SINTHIOU EL MODY BA",
  "SINTHIOU NIANA BA",
  "SINTHIOU OURA BA",
  "SOUTOUBA PEUL",
  "TEMASSOU",
  "TINCOLY",
  "BOUTOUNGCOWORA",
  "DANE NIACO",
  "DIABACK BADANE",
  "GORO MANDING",
  "KATOP",
  "KAYACOUSSA",
  "MARYCOUNDA",
  "MEDINA KAYA DIA",
  "MEDINA THIOWENE",
  "NDOGA BEULEUP",
  "PASS NDONGO",
  "PATHIAB",
  "SAMBA NDIOUKA",
  "SARE DOUNDOU",
  "SARE NIANA DEME",
  "SARE OURO NDOUGUEL",
  "SARE THILLA",
  "SINTHIOU COLIBAMA",
  "SINTHIOU DIABACK",
  "SINTHIO DIAMPOULO",
  "SINTHIOU GABABA",
  "SINTHIOUTALLEL",
  "THIEWOL",
  "VELINGARADIOUTE",
  "BANDIAGARA SANE",
  "BANNY PELLY SISSAO",
  "DJINESOUTOU SARENOH",
  "GOLODING",
  "KOULICOUNDA",
  "KOUTHIACOTO DASARA",
  "MEDINA DIAKHAO OULY",
  "MEDINA TOMBO",
  "NDEMOU GAO",
  "NDEMOU GORSOUBE",
  "NDEMOU MAMADOU",
  "NDIAYENE",
  "NDOGA BABACAR",
  "NDOGA SAMBA",
  "SAMBA KHOURADIA WOLOF",
  "SAMBA KOURADIA PEUL",
  "SARE BAMAL",
  "SARE DAWA",
  "SARE DIADIE",
  "SARE PATHE GABEL",
  "SARE SAMBA DIALLO",
  "SEOROCOTO PEUL",
  "SINTHIOU IBRAHIMA DOUMBOUYA",
  "SINTHIOU KAKARA",
  "SINTHIOU SAMBA DIOUKA",
  "SINTHIOU SOUF",
  "SINTHIOU YAMADOU",
  "SOUARECOUNDA",
  "ANIDA",
  "BANDIAGARA",
  "BANFARA GOUREL",
  "BANTANTINTI",
  "BARKAYEL (COUMBA KOULOU)",
  "DAR SALAM",
  "DAR SALAM PEULH",
  "DIADALA",
  "DIARRA",
  "DIARRA BOUGOU",
  "DJINKORE ASILE",
  "DJINKORE MANDING (BANTANKHOTO)",
  "DJINKORE MANFING",
  "DJINKORE PEULH",
  "FARABA",
  "FODECOUNDA ANSOU( BAYOCOUNDA)",
  "FODECOUNDA SADIO",
  "GALLE BO",
  "GODIOYEL (NIANGIRI )",
  "GUENETTO",
  "KANDERY DEMBA NDAO",
  "KENIABA (SARE ALADJI)",
  "KENIDALA THIATHIORO",
  "KEREWANE FAFIDJI",
  "KEREWANE NGOYE",
  "KOULARE",
  "KOUNKOUBA",
  "KOUNTOU DIOMBO (DJINKONE KOUNTOU)",
  "LAMOYE (BANFARA BOLY)",
  "MADINA GUENOTTO",
  "MADINA HAROUNA",
  "MADINA HEREMANKONO",
  "MAKA MEDINA",
  "MANDIANCOUNDA (SARE KALY)",
  "MEDINA DIALOUBE",
  "MEDINA SIBIKILING",
  "MEDINA YERA",
  "MISSIRAH SARAKHOLE (BABOKE)",
  "NEMA MOUSSA",
  "NEMATABA",
  "NETTEBOULOU",
  "OUNDOUNDOU DIAKHA",
  "OUNDOUNDOU DIAWARA (OUNDOUNDOU FADY SOW)",
  "OUNDOUNDOU KOUTHIA (SAMBA KOUTHIA)",
  "OUNDOUNDOU MAKHAN",
  "OUNDOUNDOU MEDINA NDIAYE",
  "PADANDA",
  "PANTHIAN DIOBO",
  "SARE BOURE",
  "SARE MBANDY",
  "SARE MOUDOU I",
  "SARE MOUDOU II",
  "SARE MOUDOU BA",
  "SARE MOUDOU DIAO",
  "SARE NDOUKE",
  "SARE NGABA",
  "SARE NIANA I",
  "SARE NIANA II (NIANACOUNDA)",
  "SARE SALOUM",
  "SARE TOUNKE",
  "SEGOU COURA",
  "SINTHIOU DIECKA (DJINKORI BABA GALLE)",
  "SINTHIOU KALY RENANE",
  "SINTHIOU OUMAR KOUBIA",
  "SINTHIOU VELINGARA",
  "SITAOULE MANDINGUE (SITAOULE BOURE CAMARA)",
  "SOUROUYEL",
  "SYLLABE",
  "TEMENTO PATHE",
  "THIARA (SINTHIOU YORO EDDE)",
  "TOUBA DAROU SALAM",
  "TOUBA SARAKHOLE",
  "TOUREMAN",
  "VELINGARA TOUNKE (SARE TOUNKE)",
  "WAKILIBOUGOU",
  "H1 FOULANKANE",
  "H1 SINTHIOU BOH",
  "H1 TOUBA FARABA",
  "H1 GUENETTO BAME",
  "AMADJI",
  "SEBOU",
  "DJIMBE",
  "GANGALA",
  "AROUNDOU",
  "BALLOU",
  "DEDJI",
  "DEBEKHOULE",
  "YAFERA",
  "KOUNGANY (GOUREL HAI)",
  "GOLMY",
  "FONGOLIMBI 1",
  "KOBOYE",
  "KOUNSY",
  "LESFALO",
  "MADIHOU",
  "MAROUGOU",
  "NIANGALANKOME",
  "SAMBANGALOU",
  "SECRETA",
  "SODIORE",
  "TEMBERY",
  "TOUMANIA",
  "WALLAN KINGUI",
  "WALLAN SINTHIOUROU",
  "WASSAYA",
  "H1 HORE FELO FODEYABE",
  "H1 NIANGUI BOLY",
  "H1 THIEOUNE",
  "H2 LOMBEL",
  "H2 ROUNDE",
  "FONGOLIMBI 2"
];

export default VILLAGES;
