<#
PowerShell helper to test inserting a complaint into Supabase via the REST API.
- Reads REACT_APP_SUPABASE_URL and REACT_APP_SUPABASE_ANON_KEY from ../.env if present.
- Falls back to prompting the user.
- Posts a small JSON payload to /rest/v1/complaints and prints the result.

USAGE:
  pwsh .\tools\test_supabase_insert.ps1

Security: do NOT paste or share your anon key publicly. This script prints responses that may contain error details but will not echo the key.
#>

# Resolve repo root (assumes script is in repo/tools)
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$repoRoot = Resolve-Path (Join-Path $scriptDir '..')
$envPath = Join-Path $repoRoot '.env'

$env = @{}
if (Test-Path $envPath) {
    Write-Host "Found .env at $envPath, attempting to read REACT_APP_SUPABASE_URL and REACT_APP_SUPABASE_ANON_KEY..."
    try {
        Get-Content $envPath -ErrorAction Stop | ForEach-Object {
            if ($_ -match '^[\s#]*$') { return }
            if ($_ -match '^[\s#]*([^=\s]+)\s*=\s*(.*)$') {
                $k = $matches[1].Trim()
                $v = $matches[2].Trim()
                # Remove surrounding quotes if present
                if ($v.StartsWith('"') -and $v.EndsWith('"')) { $v = $v.Substring(1, $v.Length - 2) }
                if ($v.StartsWith("'") -and $v.EndsWith("'")) { $v = $v.Substring(1, $v.Length - 2) }
                $env[$k] = $v
            }
        }
    } catch {
        Write-Warning "Failed to read .env: $_"
    }
}

# Helper to prompt securely for anon key
function Read-AnonKey([string]$prompt) {
    try {
        if ($Host.UI.SupportsVirtualTerminal) {
            # Use Read-Host -AsSecureString then convert for header
            $s = Read-Host -Prompt $prompt -AsSecureString
            $b = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($s)
            $plain = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($b)
            [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b)
            return $plain
        } else {
            return Read-Host -Prompt $prompt
        }
    } catch {
        return Read-Host -Prompt $prompt
    }
}

$url = $env['REACT_APP_SUPABASE_URL']
$key = $env['REACT_APP_SUPABASE_ANON_KEY']
$serviceKey = $env['REACT_APP_SUPABASE_SERVICE_KEY']

if (![string]::IsNullOrWhiteSpace($url)) { Write-Host "Using REACT_APP_SUPABASE_URL from .env: $url" }
if (![string]::IsNullOrWhiteSpace($key)) { Write-Host "Using REACT_APP_SUPABASE_ANON_KEY from .env (hidden)" }

if (![string]::IsNullOrWhiteSpace($url) -and !$url.StartsWith('http')) {
    # often people set only hostname, add https if missing
    $url = 'https://' + $url
}

if (![string]::IsNullOrWhiteSpace($url) -and [string]::IsNullOrWhiteSpace($key)) {
    $key = Read-AnonKey -prompt 'Supabase ANON key (will not be echoed):'
}

if ([string]::IsNullOrWhiteSpace($url)) {
    $url = Read-Host -Prompt 'Supabase project URL (for example: https://yourproject.supabase.co)'
}
if ([string]::IsNullOrWhiteSpace($key)) {
    $key = Read-AnonKey -prompt 'Supabase ANON key (will not be echoed):'
}

if ([string]::IsNullOrWhiteSpace($url) -or [string]::IsNullOrWhiteSpace($key)) {
    Write-Error "Missing Supabase URL or anon key. Aborting."
    exit 2
}

# Build test payload with randomized id
$payloadObj = @{ 
    # Use a proper UUID for id so Postgres UUID columns accept the value
    id = [guid]::NewGuid().ToString()
    parcel_number = "TEST-PS-" + (Get-Random -Maximum 1000000)
    date = (Get-Date).ToString("o")
    activity = "smoke-test"
    commune = "TEST"
    village = "TestVillage"
    complainant_name = "Test User"
    complaint_reason = "smoke test"
    complaint_reception_mode = "Auto saisine"
    complaint_category = "non_sensible"
    complaint_description = "Payload generated by tools/test_supabase_insert.ps1"
    expected_resolution = "None"
    data = @{ local = 'smoke' }
    source = "client"
    created_at = (Get-Date).ToString("o")
}

$payload = ConvertTo-Json -InputObject @($payloadObj) -Depth 10

$headers = @{
    'apikey' = $key
    'Authorization' = "Bearer $key"
    'Content-Type' = 'application/json'
    'Prefer' = 'return=representation'
}

$uri = "$url/rest/v1/complaints"

Write-Host "Posting to $uri" -ForegroundColor Cyan
Write-Host "Payload to send:" -ForegroundColor Cyan
Write-Host $payload
try {
    $resp = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $payload -ContentType 'application/json' -ErrorAction Stop
    Write-Host "\nSUCCESS: Supabase returned (response object):" -ForegroundColor Green
    $resp | ConvertTo-Json -Depth 10 | Write-Host
    Write-Host "\nInserted row preview (first element if array):" -ForegroundColor Green
    if ($resp -is [System.Array]) { $first = $resp[0]; $first | ConvertTo-Json -Depth 10 | Write-Host } else { $resp | ConvertTo-Json -Depth 10 | Write-Host }
    exit 0
} catch {
    Write-Host "\nERROR: Supabase or HTTP client returned an error." -ForegroundColor Red
    if ($_.Exception -and $_.Exception.Response) {
        try {
            $stream = $_.Exception.Response.GetResponseStream()
            $sr = New-Object System.IO.StreamReader($stream)
            $body = $sr.ReadToEnd(); $sr.Close()
            Write-Host "HTTP response body:" -ForegroundColor Yellow
            Write-Host $body
        } catch {
            Write-Host "Failed to read HTTP response body: $_"
        }
    } else {
        Write-Host $_.Exception.Message
    }
    # If we have a service_role key configured in .env, attempt the same request with it
    if (-not [string]::IsNullOrWhiteSpace($serviceKey)) {
        Write-Host "`nDetected REACT_APP_SUPABASE_SERVICE_KEY in .env - attempting retry with service_role key (key will not be printed)." -ForegroundColor Cyan
        try {
            $sHeaders = @{
                'apikey' = $serviceKey
                'Authorization' = "Bearer $serviceKey"
                'Content-Type' = 'application/json'
                'Prefer' = 'return=representation'
            }
            Write-Host "Posting again using service_role key..." -ForegroundColor Cyan
            $resp2 = Invoke-RestMethod -Uri $uri -Method Post -Headers $sHeaders -Body $payload -ContentType 'application/json' -ErrorAction Stop
            Write-Host "`nSUCCESS with service_role: Supabase returned (response object):" -ForegroundColor Green
            $resp2 | ConvertTo-Json -Depth 10 | Write-Host
            exit 0
        } catch {
            Write-Host "`nService-role retry failed." -ForegroundColor Red
            if ($_.Exception -and $_.Exception.Response) {
                try {
                    $stream = $_.Exception.Response.GetResponseStream()
                    $sr = New-Object System.IO.StreamReader($stream)
                    $body = $sr.ReadToEnd(); $sr.Close()
                    Write-Host "HTTP response body (service-role attempt):" -ForegroundColor Yellow
                    Write-Host $body
                } catch {
                    Write-Host "Failed to read HTTP response body for service-role attempt: $($_.Exception.Message)"
                }
            } else {
                Write-Host $_.Exception.Message
            }
            exit 4
        }
    }
    exit 3
}
